[project]
name = "synthetic-data-gen-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.8.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
    "streamlit-sortables>=0.3.1",
]
