from app.generators.customer_master import generate_customer_master
from app.generators.vendor_master import generate_vendor_master
from app.generators.revenue import generate_revenue_invoices
from app.generators.purchases import generate_purchases
from app.generators.debtors import generate_debtors_from_invoices
from app.generators.ppe import generate_ppe_register
from app.generators.inventory import generate_inventory_snapshots
from app.generators.operational import generate_operational_dataset
